Added the --pdnsd-user option, and made the Debian rc script use it rather than trying to parse the config file itself.

diff --git a/src/rc/Debian/pdnsd.in b/src/rc/Debian/pdnsd.in
--- a/src/rc/Debian/pdnsd.in
+++ b/src/rc/Debian/pdnsd.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# $Id: pdnsd.in,v 1.1 2000/10/11 22:29:05 thomas Exp $
+# $Id: pdnsd.in,v 1.2 2000/10/13 18:18:38 thomas Exp $
 #
 # This script was written and contributed by Markus Mohr, and
 # slightly modified by me for version 1.0.6 (which obviously
@@ -10,9 +10,8 @@
 # Carsten Block has patched this with some magic so that
 # the actual script is generated by configure, and that
 # the pdnsd user is determined from pdnsd.conf
-# I changed this a little (to support whitespaces before
-# and after the '=' sign, and to ignore entries that are 
-# commented out), so if this is broken, blame me ;-)
+# I changed this a little to use the --pdnsd-user option
+# of pdnsd to determine the run_as user.
 #
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
@@ -23,8 +22,7 @@ case "$1" in
     start)
     	# Check if cache dir exists and recreate if neccessary
 	test -d @cachedir@ || mkdir @cachedir@
-	#FIXME: Was ist mit /* Kommentaren */ ????
-	RUNAS=`grep '^[^#/]run_as /etc/pdnsd.conf | sed 's/.*run_as\W*=\W*"\(.*\)";.*/\1/'`
+	RUNAS=`@prefix@/sbin/pdnsd --pdnsd-user` || echo -n " failed"
 	[ -z "$RUNAS" ] && RUNAS=nobody
 	chown $RUNAS @cachedir@
 	echo -n "Starting domain name service: pdnsd"
