Revert the last commit. It breaks the rc scripts by spamming them with make style variable expansions.

diff --git a/src/rc/Debian/pdnsd.in b/src/rc/Debian/pdnsd.in
--- a/src/rc/Debian/pdnsd.in
+++ b/src/rc/Debian/pdnsd.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# $Id: pdnsd.in,v 1.3 2001/05/04 20:13:44 tmm Exp $
+# $Id: pdnsd.in,v 1.4 2001/05/04 21:58:26 tmm Exp $
 #
 # This script was written and contributed by Markus Mohr, and
 # slightly modified by me for version 1.0.6 (which obviously
@@ -16,25 +16,25 @@
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
 
-test -x @sbindir@/pdnsd || exit 0
+test -x @prefix@/sbin/pdnsd || exit 0
 
 case "$1" in
     start)
     	# Check if cache dir exists and recreate if neccessary
 	test -d @cachedir@ || mkdir @cachedir@
-	RUNAS=`@sbindir@/pdnsd --pdnsd-user` || echo -n " failed"
+	RUNAS=`@prefix@/sbin/pdnsd --pdnsd-user` || echo -n " failed"
 	[ -z "$RUNAS" ] && RUNAS=nobody
 	chown $RUNAS @cachedir@
 	echo -n "Starting domain name service: pdnsd"
 	start-stop-daemon --start --quiet --pidfile /var/run/pdnsd.pid --name pdnsd \
-	--exec @sbindir@/pdnsd -- --daemon -p /var/run/pdnsd.pid \
+	--exec @prefix@/sbin/pdnsd -- --daemon -p /var/run/pdnsd.pid \
 	|| echo -n " failed"
 	echo "."
     ;;
 
     stop)
 	echo -n "Stopping domain name service: pdnsd"
-	start-stop-daemon --stop --quiet  --pidfile /var/run/pdnsd.pid --name pdnsd --exec @sbindir@/pdnsd \
+	start-stop-daemon --stop --quiet  --pidfile /var/run/pdnsd.pid --name pdnsd --exec @prefix@/sbin/pdnsd \
 	|| echo -n " failed"
 	echo "."
     ;;
